stages:
  - deploy

pages:
  stage: deploy
  variables:
    FF_USE_FASTZIP: "true"
    ARTIFACT_COMPRESSION_LEVEL: "fastest"
  script: 
    - echo "Deploying pages"
  artifacts:
    paths:
      - public
  only:
    - main
